app/main/forms.py
from flask_wtf import Form
from wtforms.fields import StringField, SubmitField
from wtforms.validators import Required


class LoginForm(Form):
    """Accepts a nickname and a room."""
    name = StringField('Name', validators=[Required()])
    room = StringField('Room', validators=[Required()])
    submit = SubmitField('Enter Chatroom')

app/__init__.py
from flask import Flask
from flask_socketio import SocketIO

socketio = SocketIO()


def create_app(debug=False):
    """Create an application."""
    app = Flask(__name__)
    app.debug = debug
    app.config['SECRET_KEY'] = 'gjr39dkjn344_!67#'

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    socketio.init_app(app)
    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import routes, events

app/main/routes.py
from flask import session, redirect, url_for, render_template, request
from . import main
from .forms import LoginForm


@main.route('/', methods=['GET', 'POST'])
def index():
    """Login form to enter a room."""
    form = LoginForm()
    if form.validate_on_submit():
        session['name'] = form.name.data
        session['room'] = form.room.data
        return redirect(url_for('.chat'))
    elif request.method == 'GET':
        form.name.data = session.get('name', '')
        form.room.data = session.get('room', '')
    return render_template('index.html', form=form)


@main.route('/chat')
def chat():
    """Chat room. The user's name and room must be stored in
    the session."""
    name = session.get('name', '')
    room = session.get('room', '')
    if name == '' or room == '':
        return redirect(url_for('.index'))
    return render_template('chat.html', name=name, room=room)

app/templates/chat.html
<html>
    <head>
        <title>Welcome to {{ room }}</title>
        <script type="text/javascript" src="//code.jquery.com/jquery-1.4.2.min.js"></script>
        <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.6/socket.io.min.js"></script>
        <script type="text/javascript" charset="utf-8">
            var socket;
            $(document).ready(function(){
                socket = io.connect('http://' + document.domain + ':' + location.port + '/chat');
                socket.on('connect', function() {
                    socket.emit('joined', {});
                });
                socket.on('status', function(data) {
                    $('#chat').val($('#chat').val() + '<' + data.msg + '>\n');
                    $('#chat').scrollTop($('#chat')[0].scrollHeight);
                });
                socket.on('message', function(data) {
                    $('#chat').val($('#chat').val() + data.msg + '\n');
                    $('#chat').scrollTop($('#chat')[0].scrollHeight);
                });
                $('#text').keypress(function(e) {
                    var code = e.keyCode || e.which;
                    if (code == 13) {
                        text = $('#text').val();
                        $('#text').val('');
                        socket.emit('text', {msg: text});
                    }
                });
            });
            function leave_room() {
                socket.emit('left', {}, function() {
                    socket.disconnect();

                    // go back to the login page
                    window.location.href = "{{ url_for('main.index') }}";
                });
            }
        </script>
    </head>

    <style>

    textarea{
        /* padding-left: 10%;
        padding-right: 10%;
        padding-top: 10%;
        padding-bottom: 10; */
     display: block;

    margin-left: auto;
    margin-right: auto;
    background-color: rgba(13,2,2,0.171);    
    font-family:cursive;
    color: aliceblue;   
    }


  body{
      background: url('https://images.unsplash.com/photo-1581879608672-f4b28f26c348?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MjN8fHRyaWFsJTIwcm9vbXxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60');
      background-position: center;
      background-repeat: no-repeat;
      background-size: cover;
  }
  input{
    display: block;

margin-left: auto;
margin-right: auto;

background-color: rgba(3, 2, 2, 0.171);   
  }
  
  a{
    margin:0 auto;    
   display:block;
   color: aliceblue;
   font-family: cursive;
  }

  h1{
      font-family: cursive;
      font-size:x-large;
      color: aliceblue;
  }


    </style>
    <body>
        <h1>Room {{ room }}</h1>
        <textarea id="chat" cols="80" rows="20"></textarea><br><br>
        <input id="text" size="80" placeholder="Enter your message here"><br><br>
     

     

        <!-- <input type="file"
       id="avatar" name="avatar"
       accept="image/png, image/jpeg"> -->

        <a href="#" align="middle"  onclick="leave_room();">Leave this room</a>
    </body>
</html>

app/templates/index.html
<html>
    <head>
        <title>ChatRoom</title>
    </head>
    <style>
        body{
            background: url('https://images.unsplash.com/photo-1571992579655-8134e2b8df0b?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NDl8fHJvb218ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60');
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
        }
        form{
            margin-left: auto;
            margin-right: auto;
           
            color:aliceblue;
            font-family: cursive;
            font-weight: bolder;
          height: 50%;
          padding-top: 20%;
        }
        h1{
            color: aliceblue;
            font-family: cursive;
            font-weight: bolder;
        }
      
    </style>
    <body>
        <h1>ChatRoom</h1>
        <div class ="Form">
        <form method="POST" align="middle" width="60" height="60">
            {{ form.hidden_tag() }}
            {{ form.name.label }}: {{ form.name() }} {% for error in form.name.errors %}{{ error }}{% endfor %}<br>
            {{ form.room.label }}: {{ form.room() }} {% for error in form.room.errors %}{{ error }}{% endfor %}<br>
            {{ form.submit() }}
        </form>
        </div>
    </body>
</html>